### ISSUE TITLE
TODO list for Server Code Reboot

### ISSUE THREAD

**Issue by icydee** [plainblack/Lacuna-Server-Open#435]
Things that need to be done in the REBOOT code but which don't need a separate issue.

- [ ] Ensure all Empire API calls use named calling convention, and document calls.
- [ ] All Ship related calls to be rewritten to use fleets.
- [ ] All new API calls to return status block only on request, or when significant changes server side.
- [ ] lots more things (please add as you find them)
